name: NightVision
version: '${project.version}'
main: skh6075.nightvision.NightVision
api-version: 1.19
authors: [ skh6075 ]
website: https://github.com/skh6075

commands:
  야간투시:
    description: 야간투시 명령어입니다.
    aliases: ['야투']